function identifierConfig = get_identifier_target_config()
%GET_IDENTIFIER_TARGET_CONFIG Default P3 identifier target/feature config.
%   P3 still defaults to eta-hat identification, while preserving the
%   theta-hat interface as a reserved extension target.

identifierConfig = struct();
identifierConfig.mode = 'eta';
identifierConfig.targetNames = { ...
    'eta_roll_hat', ...
    'eta_pitch_hat', ...
    'eta_yaw_hat', ...
    'eta_total_hat'};
identifierConfig.targetNamesTheta = { ...
    'left_inner_wing', ...
    'left_outer_wing', ...
    'right_inner_wing', ...
    'right_outer_wing', ...
    'left_horizontal_tail', ...
    'right_horizontal_tail', ...
    'vertical_tail', ...
    'left_aileron_eff', ...
    'right_aileron_eff', ...
    'elevator_eff', ...
    'rudder_eff', ...
    'thrust_eff'};

identifierConfig.featureMode = 'summary_plus_residual_energy';
identifierConfig.sequenceLength = 40;
identifierConfig.sequenceDt = 0.1;
identifierConfig.historyDuration = 8.0;
identifierConfig.featureModesSupported = { ...
    'summary', ...
    'sequence', ...
    'summary_plus_residual_energy', ...
    'summary_plus_cross_channel_stats', ...
    'hybrid_sequence_summary'};

identifierConfig.residualFilterMode = 'moving_average';
identifierConfig.residualWindowLength = 5;
identifierConfig.nominalPredictorMode = 'simple_airframe';
identifierConfig.primaryModelType = 'ridge';
identifierConfig.supportedModelTypes = { ...
    'ridge', ...
    'shallow_mlp', ...
    'sequence_mlp_placeholder', ...
    'ensemble_summary'};
end
