function identifierConfig = get_identifier_target_config()
%GET_IDENTIFIER_TARGET_CONFIG Default P2 online identifier configuration.
%   P2 defaults to eta-hat identification. Theta-hat mode is retained as a
%   reserved interface for the next iteration.

identifierConfig = struct();
identifierConfig.mode = 'eta';
identifierConfig.targetNames = { ...
    'eta_roll_hat', ...
    'eta_pitch_hat', ...
    'eta_yaw_hat', ...
    'eta_total_hat'};
identifierConfig.featureMode = 'summary';
identifierConfig.sequenceLength = 25;
identifierConfig.sequenceDt = 0.1;
identifierConfig.historyDuration = 5.0;
identifierConfig.primaryModelType = 'ridge';
identifierConfig.supportedModelTypes = {'ridge', 'mlp'};
identifierConfig.targetNamesTheta = { ...
    'left_inner_wing', ...
    'left_outer_wing', ...
    'right_inner_wing', ...
    'right_outer_wing', ...
    'left_horizontal_tail', ...
    'right_horizontal_tail', ...
    'vertical_tail', ...
    'left_aileron_eff', ...
    'right_aileron_eff', ...
    'elevator_eff', ...
    'rudder_eff', ...
    'thrust_eff'};
end
