function identifierConfig = get_identifier_target_config()
%GET_IDENTIFIER_TARGET_CONFIG Default identifier target and feature config.
%   P3.5 still defaults to eta-hat identification while keeping the
%   theta-hat interface available for later replacement.

identifierConfig = struct();
identifierConfig.mode = 'eta';
identifierConfig.targetNames = { ...
    'eta_roll_hat', ...
    'eta_pitch_hat', ...
    'eta_yaw_hat', ...
    'eta_total_hat'};
identifierConfig.targetNamesTheta = { ...
    'left_inner_wing', ...
    'left_outer_wing', ...
    'right_inner_wing', ...
    'right_outer_wing', ...
    'left_horizontal_tail', ...
    'right_horizontal_tail', ...
    'vertical_tail', ...
    'left_aileron_eff', ...
    'right_aileron_eff', ...
    'elevator_eff', ...
    'rudder_eff', ...
    'thrust_eff'};

identifierConfig.featureMode = 'normalized_summary';
identifierConfig.sequenceLength = 50;
identifierConfig.sequenceDt = 0.1;
identifierConfig.historyDuration = 10.0;
identifierConfig.featureModesSupported = { ...
    'summary', ...
    'sequence', ...
    'summary_plus_residual_energy', ...
    'summary_plus_cross_channel_stats', ...
    'hybrid_sequence_summary', ...
    'normalized_summary', ...
    'residual_coupling_summary', ...
    'hybrid_sequence_summary_v2'};

identifierConfig.featureModeDescriptions = struct( ...
    'summary', 'Compact mean/std/peak/slope/energy features for simple linear models.', ...
    'sequence', 'Raw stacked state-input-residual sequence for temporal placeholder models.', ...
    'summary_plus_residual_energy', 'Summary features with per-channel residual energy and peaks.', ...
    'summary_plus_cross_channel_stats', 'Summary features with input-state and residual cross-channel correlations.', ...
    'hybrid_sequence_summary', 'Hybrid summary plus raw sequence output for richer models.', ...
    'normalized_summary', 'Summary features augmented with normalized residual statistics and filter deltas.', ...
    'residual_coupling_summary', 'Summary features focused on channel coupling, ratios, and response delay proxies.', ...
    'hybrid_sequence_summary_v2', 'Hybrid sequence plus normalized, coupling, and filtered-delta summaries.');

identifierConfig.residualFilterMode = 'moving_average';
identifierConfig.residualWindowLength = 7;
identifierConfig.nominalPredictorMode = 'simple_airframe';
% When true, simulate_identifier_timeseries pre-computes every supported
% featureMode and stores them in sample.featureModeReadyData. Set this to
% true in dataset-generation contexts that feed multi-config sweeps; leave
% it false (the default) for single-config online assessment, which only
% needs the active featureMode and otherwise pays a ~8x feature-build cost.
identifierConfig.precomputeAllFeatureModes = false;
identifierConfig.primaryModelType = 'ridge';
identifierConfig.supportedModelTypes = { ...
    'ridge', ...
    'shallow_mlp', ...
    'sequence_placeholder', ...
    'ensemble_summary'};
end
