function generate_architecture_diagrams()
%GENERATE_ARCHITECTURE_DIAGRAMS Write architecture/program-flow markdown diagrams.

rootDir = fileparts(fileparts(mfilename('fullpath')));
write_text(fullfile(rootDir, 'docs', 'system_architecture.md'), system_architecture_text());
write_text(fullfile(rootDir, 'docs', 'program_flow.md'), program_flow_text());
fprintf('Architecture diagram markdown generated.\n');
end

function write_text(pathName, txt)
fid = fopen(pathName, 'w');
fprintf(fid, '%s', txt);
fclose(fid);
end

function txt = system_architecture_text()
txt = [ ...
"# System Architecture" newline newline ...
"```mermaid" newline ...
"flowchart LR" newline ...
"  A[Damage Parameterization] --> B[Nominal Predictor]" newline ...
"  B --> C[Residual Generator / Filter]" newline ...
"  C --> D[Identifier]" newline ...
"  D --> E[Controllability Evaluation]" newline ...
"  E --> F[Trim Feasibility]" newline ...
"  F --> G[Decision Manager]" newline ...
"  D --> H[Visualization Interface]" newline ...
"  G --> H" newline ...
"  G --> I[Closed-loop Evaluation]" newline ...
"  D --> I" newline ...
"```" newline newline ...
"The online chain is separated from offline training so the deployed model path can evolve without changing the assessment backbone." newline];
txt = char(txt);
end

function txt = program_flow_text()
txt = [ ...
"# Program Flow" newline newline ...
"## Main Model Flow" newline newline ...
"```mermaid" newline ...
"flowchart TD" newline ...
"  M1[6DOF FixedWing] --> M2[Sensor Output Bus]" newline ...
"  M2 --> M3[Online Damage Identifier]" newline ...
"  M3 --> M4[Decision Logic]" newline ...
"  M4 --> M5[Actuator / Propulsion]" newline ...
"  M5 --> M1" newline ...
"  M3 --> M6[Visualization Interface]" newline ...
"```" newline newline ...
"## Offline Training vs Online Inference" newline newline ...
"```mermaid" newline ...
"flowchart LR" newline ...
"  D1[Dataset Generation] --> D2[Feature Builder]" newline ...
"  D2 --> D3[Identifier Training]" newline ...
"  D3 --> D4[Best Model Selection]" newline ...
"  D4 --> O1[Online Inference]" newline ...
"  O1 --> O2[Assessment and Decision]" newline ...
"```" newline];
txt = char(txt);
end
