function generate_presentation_diagrams()
%GENERATE_PRESENTATION_DIAGRAMS Write presentation-oriented flow diagrams.

rootDir = fileparts(fileparts(mfilename('fullpath')));
fid = fopen(fullfile(rootDir, 'docs', 'presentation_flow.md'), 'w');
fprintf(fid, '%s', presentation_flow_text());
fclose(fid);
fprintf('Presentation flow markdown generated.\n');
end

function txt = presentation_flow_text()
txt = [ ...
"# Presentation Flow" newline newline ...
"## 1. Project Main Flow" newline newline ...
"```mermaid" newline ...
"flowchart LR" newline ...
"  A[Damage Input] --> B[Residual-driven Identifier]" newline ...
"  B --> C[Controllability and Trim]" newline ...
"  C --> D[Decision Output]" newline ...
"  D --> E[Visualization and Evaluation]" newline ...
"```" newline ...
"This figure explains the end-to-end research chain at a high level." newline ...
"It is suitable for the opening system overview slide." newline newline ...
"## 2. Identifier Training Flow" newline newline ...
"```mermaid" newline ...
"flowchart TD" newline ...
"  T1[Scenario Generation] --> T2[Nominal Prediction]" newline ...
"  T2 --> T3[Residual / Feature Extraction]" newline ...
"  T3 --> T4[Model Training and Sweep]" newline ...
"  T4 --> T5[Best Configuration]" newline ...
"```" newline ...
"This figure separates data generation, feature engineering, and training." newline ...
"Use it when introducing the offline part of the project." newline newline ...
"## 3. Identified Mode vs Oracle Mode" newline newline ...
"```mermaid" newline ...
"flowchart LR" newline ...
"  O1[True theta_d] --> O2[Oracle Assessment]" newline ...
"  I1[Residual Features] --> I2[Identifier]" newline ...
"  I2 --> I3[Identified Assessment]" newline ...
"  O2 --> C[Consistency Comparison]" newline ...
"  I3 --> C" newline ...
"```" newline ...
"This figure emphasizes that the same decision chain is fed by either true damage or identified damage summaries." newline ...
"Use it to explain fairness of closed-loop comparison." newline newline ...
"## 4. Decision Consistency Evaluation" newline newline ...
"```mermaid" newline ...
"flowchart TD" newline ...
"  C1[eta Error] --> C4[Closed-loop Metrics]" newline ...
"  C2[Trim Match] --> C4" newline ...
"  C3[Decision Match / Unsafe Undertrigger] --> C4" newline ...
"```" newline ...
"This figure focuses on evaluation outputs rather than plant details." newline ...
"Use it on result summary slides." newline];
txt = char(txt);
end
