function generate_architecture_diagrams()
%GENERATE_ARCHITECTURE_DIAGRAMS Write architecture/program-flow markdown diagrams.

rootDir = fileparts(fileparts(mfilename('fullpath')));
write_text(fullfile(rootDir, 'docs', 'system_architecture.md'), system_architecture_text());
write_text(fullfile(rootDir, 'docs', 'program_flow.md'), program_flow_text());
fprintf('Architecture diagram markdown generated.\n');
end

function write_text(pathName, txt)
fid = fopen(pathName, 'w');
fprintf(fid, '%s', txt);
fclose(fid);
end

function txt = system_architecture_text()
txt = join_lines({ ...
    '# System Architecture', ...
    '', ...
    '## Current Block Diagram', ...
    '', ...
    '```mermaid', ...
    'flowchart LR', ...
    '  subgraph OFF[Offline training and model selection]', ...
    '    A1[Scenario generation] --> A2[Nominal predictor]', ...
    '    A2 --> A3[Residual filtering]', ...
    '    A3 --> A4[Feature builder]', ...
    '    A4 --> A5[Identifier training]', ...
    '    A5 --> A6[Hyperparameter sweep]', ...
    '    A6 --> A7[Best identifier model]', ...
    '  end', ...
    '  subgraph ON[Timeline aware online assessment]', ...
    '    B1[Normal flight segment] --> B2[Damage gate and ramp]', ...
    '    B2 --> B3[Damaged trajectory and sensor residuals]', ...
    '    B3 --> B4[Filtered residual features]', ...
    '    B4 --> B5[Damage eta identifier]', ...
    '    B5 --> B6[Control authority metrics]', ...
    '    B6 --> B7[Trim feasibility]', ...
    '    B7 --> B8[Decision manager]', ...
    '    B8 --> B9[Mode command profile]', ...
    '    B9 --> B10[Trajectory and assessment figures]', ...
    '  end', ...
    '  A7 --> B5', ...
    '  B8 --> C1[Identified vs oracle comparison]', ...
    '  B6 --> C1', ...
    '  C1 --> C2[Closed loop and demo summaries]', ...
    '```', ...
    '', ...
    'The current demo chain is explicitly staged as normal flight, damage injection, identification and assessment, and decision-command execution. Offline training remains separated from the online assessment backbone so the identifier model can evolve without changing the control-authority, trim, and decision interfaces.', ...
    '', ...
    '## Primary Runtime Signals', ...
    '', ...
    '```mermaid', ...
    'flowchart TD', ...
    '  S1[theta_d and scenario metadata] --> S2[Damage effects]', ...
    '  S2 --> S3[State and input history]', ...
    '  S3 --> S4[Residual history]', ...
    '  S4 --> S5[Feature vector]', ...
    '  S5 --> S6[eta_hat confidence uncertainty]', ...
    '  S6 --> S7[eta_roll eta_pitch eta_yaw eta_total]', ...
    '  S7 --> S8[Trim risk and decision mode]', ...
    '  S8 --> S9[Mode trace and exported figures]', ...
    '```'});
end

function txt = program_flow_text()
txt = join_lines({ ...
    '# Program Flow', ...
    '', ...
    '## Demo Timeline Flow', ...
    '', ...
    '```mermaid', ...
    'flowchart LR', ...
    '  T0[0 to 3 s normal flight] --> T1[3 s damage starts]', ...
    '  T1 --> T2[3 to 4 s damage ramp]', ...
    '  T2 --> T3[Residual features accumulate]', ...
    '  T3 --> T4[5 s assessment decision]', ...
    '  T4 --> T5[Mode command applied]', ...
    '  T5 --> T6[Trajectory speed altitude assessment export]', ...
    '```', ...
    '', ...
    '## Main Model Flow', ...
    '', ...
    '```mermaid', ...
    'flowchart TD', ...
    '  M1[6DOF FixedWing] --> M2[Sensor Output Bus]', ...
    '  M2 --> M3[Online Damage Identifier]', ...
    '  M3 --> M4[Decision Logic]', ...
    '  M4 --> M5[Actuator / Propulsion]', ...
    '  M5 --> M1', ...
    '  M3 --> M6[Visualization Interface]', ...
    '```', ...
    '', ...
    '## Offline Training vs Online Inference', ...
    '', ...
    '```mermaid', ...
    'flowchart LR', ...
    '  D1[Dataset Generation] --> D2[Feature Builder]', ...
    '  D2 --> D3[Identifier Training]', ...
    '  D3 --> D4[Best Model Selection]', ...
    '  D4 --> O1[Online Inference]', ...
    '  O1 --> O2[Assessment and Decision]', ...
    '  O2 --> O3[Demo and closed loop result summaries]', ...
    '```'});
end

function txt = join_lines(lines)
txt = char([strjoin(lines, newline), newline]);
end
