function params = init_project()
%INIT_PROJECT Initialize baseline parameters for damaged fixed-wing studies.

rootDir = fileparts(fileparts(mfilename('fullpath')));

projectDirs = {'models', 'scripts', 'functions', 'data', 'results', 'docs'};
for i = 1:numel(projectDirs)
    dirPath = fullfile(rootDir, projectDirs{i});
    if ~exist(dirPath, 'dir')
        mkdir(dirPath);
    end
end

addpath(fullfile(rootDir, 'scripts'));
addpath(fullfile(rootDir, 'functions'));
addpath(fullfile(rootDir, 'data'));

params = struct();

params.aircraft = struct( ...
    'mass', 1200.0, ...
    'wingArea', 16.2, ...
    'span', 10.9, ...
    'meanAerodynamicChord', 1.52, ...
    'inertia', diag([950.0, 1350.0, 1800.0]));

params.environment = struct( ...
    'gravity', 9.80665);

params.initial = struct( ...
    'pned_m', [0; 0; -1000], ...
    'uvw_mps', [32; 0; 0], ...
    'euler_rad', deg2rad([0; 2; 0]), ...
    'pqr_rps', [0; 0; 0]);

params.theta_d = zeros(12, 1);
params.control = struct( ...
    'trim', zeros(4, 1), ...
    'limits', ones(4, 1));

params.aero = struct( ...
    'rho0', 1.225, ...
    'CL0', 0.28, ...
    'CLalpha', 4.8, ...
    'CLde', 0.35, ...
    'CD0', 0.035, ...
    'CDk', 0.08, ...
    'CYbeta', -0.45, ...
    'Cl_da', 0.12, ...
    'Cm0', 0.02, ...
    'Cmalpha', -0.85, ...
    'Cmde', -0.9, ...
    'Cn_dr', -0.1);

params.propulsion = struct( ...
    'maxThrustN', 3200.0);

assignin('base', 'P', params);
assignin('base', 'theta_d', params.theta_d);
assignin('base', 'g0', params.environment.gravity);

disp('Project parameters loaded into base workspace: P, theta_d, g0');
end
