function params = init_project()
%INIT_PROJECT Initialize the P1 damaged-aircraft project workspace.
%
% Damage vector theta_d is a continuous 12x1 vector in [0, 1], where:
%   1  left_inner_wing
%   2  left_outer_wing
%   3  right_inner_wing
%   4  right_outer_wing
%   5  left_horizontal_tail
%   6  right_horizontal_tail
%   7  vertical_tail
%   8  left_aileron_eff
%   9  right_aileron_eff
%   10 elevator_eff
%   11 rudder_eff
%   12 thrust_eff
%
% Recommended interpretation:
%   0.0 -> no damage / full effectiveness
%   0.2 -> mild degradation
%   0.5 -> moderate degradation
%   0.8 -> severe degradation
%   1.0 -> near-total loss of the affected component

rootDir = fileparts(fileparts(mfilename('fullpath')));

projectDirs = {'models', 'scripts', 'functions', 'data', 'results', 'docs'};
for i = 1:numel(projectDirs)
    dirPath = fullfile(rootDir, projectDirs{i});
    if ~exist(dirPath, 'dir')
        mkdir(dirPath);
    end
end

addpath(fullfile(rootDir, 'scripts'));
addpath(genpath(fullfile(rootDir, 'functions')));
addpath(fullfile(rootDir, 'data'));
addpath(fullfile(rootDir, 'models'));

params = struct();

params.aircraft = struct( ...
    'mass', 1200.0, ...
    'wingArea', 16.2, ...
    'span', 10.9, ...
    'meanAerodynamicChord', 1.52, ...
    'inertia', diag([950.0, 1350.0, 1800.0]));

params.environment = struct( ...
    'gravity', 9.80665, ...
    'windLevels_mps', [0, 4, 8]);

params.initial = struct( ...
    'pned_m', [0; 0; -1000], ...
    'uvw_mps', [32; 0; 0], ...
    'euler_rad', deg2rad([0; 2; 0]), ...
    'pqr_rps', [0; 0; 0]);

params.theta_d = zeros(12, 1);
params.damageLabels = { ...
    'left_inner_wing'; ...
    'left_outer_wing'; ...
    'right_inner_wing'; ...
    'right_outer_wing'; ...
    'left_horizontal_tail'; ...
    'right_horizontal_tail'; ...
    'vertical_tail'; ...
    'left_aileron_eff'; ...
    'right_aileron_eff'; ...
    'elevator_eff'; ...
    'rudder_eff'; ...
    'thrust_eff'};

params.control = struct( ...
    'trim', zeros(4, 1), ...
    'safeCommand', [-0.02; 0.0; 0.0; 0.35], ...
    'damageThreshold', 0.7, ...
    'limits', ones(4, 1), ...
    'modeCommands', struct( ...
        'NORMAL', [0.00; 0.00; 0.00; 0.40], ...
        'STABILIZE', [-0.02; 0.00; 0.00; 0.35], ...
        'RETURN', [-0.01; 0.00; 0.00; 0.45], ...
        'DIVERT', [-0.01; 0.00; 0.02; 0.50], ...
        'EGRESS_PREP', [0.03; 0.00; 0.00; 0.60], ...
        'UNRECOVERABLE', [0.00; 0.00; 0.00; 0.70]));

params.decision = struct( ...
    'hysteresisEnabled', true, ...
    'confidenceGuardEnabled', true, ...
    'minModeDuration', 3, ...
    'etaSmoothingWindow', 5, ...
    'returnThreshold', 0.70, ...
    'divertThreshold', 0.50, ...
    'egressThreshold', 0.30, ...
    'confidenceReturnMin', 0.60, ...
    'uncertaintyHigh', 0.65);

params.aero = struct( ...
    'rho0', 1.225, ...
    'CL0', 0.28, ...
    'CLalpha', 4.8, ...
    'CLde', 0.35, ...
    'CD0', 0.035, ...
    'CDk', 0.08, ...
    'CYbeta', -0.45, ...
    'Cl_da', 0.12, ...
    'Cm0', 0.02, ...
    'Cmalpha', -0.85, ...
    'Cmde', -0.9, ...
    'Cn_dr', -0.1);

params.propulsion = struct( ...
    'maxThrustN', 3200.0);

assignin('base', 'P', params);
assignin('base', 'theta_d', params.theta_d);
assignin('base', 'g0', params.environment.gravity);

disp('Project parameters loaded into base workspace: P, theta_d, g0');
end
