function closedLoopResult = run_identifier_closed_loop_batch()
%RUN_IDENTIFIER_CLOSED_LOOP_BATCH Compare oracle and identified pipelines.

rootDir = fileparts(fileparts(mfilename('fullpath')));
run(fullfile(rootDir, 'scripts', 'init_project.m'));

datasetPath = fullfile(rootDir, 'data', 'identifier_dataset_v3.mat');
if ~isfile(datasetPath)
    generate_identifier_dataset();
end

sweepPath = fullfile(rootDir, 'results', 'identifier_hyperparam_sweep.mat');
if ~isfile(sweepPath)
    run_identifier_hyperparam_sweep();
end

D = load(datasetPath, 'identifierDataset');
H = load(sweepPath, 'sweepResult');
identifierDataset = D.identifierDataset;
bestEntry = H.sweepResult.entries(H.sweepResult.bestIndex);
identifierModel = bestEntry.identifierModel;
identifierConfig = identifierModel.config;

closedLoopSummary = repmat(empty_closed_loop_entry(), numel(identifierDataset.samples), 1);

for i = 1:numel(identifierDataset.samples)
    sample = identifierDataset.samples(i);
    theta_d = sample.theta_d;
    % Reuse the precomputed sample from the dataset to skip the two redundant
    % simulate_identifier_timeseries calls that the previous version paid for.
    oracleResult = run_online_assessment_pipeline(theta_d, [], identifierConfig, 'oracle', sample.scenarioInfo, sample);
    identifiedResult = run_online_assessment_pipeline(theta_d, identifierModel, identifierConfig, 'identified', sample.scenarioInfo, sample);

    etaTrue = [ ...
        oracleResult.oracle.ctrlMetrics.eta_roll, ...
        oracleResult.oracle.ctrlMetrics.eta_pitch, ...
        oracleResult.oracle.ctrlMetrics.eta_yaw, ...
        oracleResult.oracle.ctrlMetrics.eta_total];
    etaHat = [ ...
        identifiedResult.identified.ctrlMetrics.eta_roll, ...
        identifiedResult.identified.ctrlMetrics.eta_pitch, ...
        identifiedResult.identified.ctrlMetrics.eta_yaw, ...
        identifiedResult.identified.ctrlMetrics.eta_total];

    oracleDecision = oracleResult.oracle.decisionOutput.mode;
    identifiedDecision = identifiedResult.identified.decisionOutput.mode;
    dangerousMismatch = is_dangerous_mismatch(oracleDecision, identifiedDecision, identifiedResult.identified.identifierOutput.confidence);
    conservativeDecision = is_strictly_conservative(oracleDecision, identifiedDecision);
    overtrigger = conservativeDecision && ismember(upper(identifiedDecision), {'STABILIZE', 'DIVERT', 'EGRESS_PREP'}) && ...
        ismember(upper(oracleDecision), {'NORMAL', 'RETURN'});
    conservativeCorrect = conservativeDecision && ~dangerousMismatch && ~overtrigger;
    unsafeUndertrigger = is_more_aggressive(identifiedDecision, oracleDecision);

    closedLoopSummary(i).scenarioId = i;
    closedLoopSummary(i).scenarioType = sample.scenarioInfo.scenarioType;
    closedLoopSummary(i).damageCategory = char(sample.damageCategory);
    closedLoopSummary(i).severity = sample.scenarioInfo.severity;
    closedLoopSummary(i).theta_d = theta_d;
    closedLoopSummary(i).etaTrue = etaTrue;
    closedLoopSummary(i).etaHat = etaHat;
    closedLoopSummary(i).etaErrorMean = mean(abs(etaHat - etaTrue));
    closedLoopSummary(i).oracleDecision = oracleDecision;
    closedLoopSummary(i).identifiedDecision = identifiedDecision;
    closedLoopSummary(i).decisionMatch = identifiedResult.decisionMatch;
    closedLoopSummary(i).controllabilityMatch = identifiedResult.controllabilityMatch;
    closedLoopSummary(i).trimRiskOracle = oracleResult.oracle.trimInfo.trimRiskLevel;
    closedLoopSummary(i).trimRiskIdentified = identifiedResult.identified.trimInfo.trimRiskLevel;
    closedLoopSummary(i).trimInfoConsistency = identifiedResult.trimMatch;
    closedLoopSummary(i).oracleIsTrimmable = oracleResult.oracle.trimInfo.is_trimmable;
    closedLoopSummary(i).identifiedIsTrimmable = identifiedResult.identified.trimInfo.is_trimmable;
    closedLoopSummary(i).identifierConfidence = identifiedResult.identified.identifierOutput.confidence;
    closedLoopSummary(i).identifierUncertainty = identifiedResult.identified.identifierOutput.uncertaintyScore;
    closedLoopSummary(i).conservativeDecision = conservativeDecision;
    closedLoopSummary(i).dangerousMismatch = dangerousMismatch;
    closedLoopSummary(i).conservativeCorrect = conservativeCorrect;
    closedLoopSummary(i).conservativeOvertrigger = overtrigger;
    closedLoopSummary(i).unsafeUndertrigger = unsafeUndertrigger;
end

summaryTable = closed_loop_table(closedLoopSummary);
closedLoopResult = struct();
closedLoopResult.closedLoopSummary = closedLoopSummary;
closedLoopResult.summaryTable = summaryTable;
closedLoopResult.averageEtaError = mean([closedLoopSummary.etaErrorMean]);
closedLoopResult.decisionMatchRate = mean([closedLoopSummary.decisionMatch]);
closedLoopResult.controllabilityMatchRate = mean([closedLoopSummary.controllabilityMatch]);
closedLoopResult.trimMatchRate = mean([closedLoopSummary.trimInfoConsistency]);

primaryResultPath = fullfile(rootDir, 'results', 'identifier_closed_loop_batch.mat');
save(primaryResultPath, 'closedLoopSummary', 'summaryTable', 'closedLoopResult');
copyfile(primaryResultPath, fullfile(rootDir, 'results', 'identified_vs_oracle_summary.mat'));
writetable(summaryTable, fullfile(rootDir, 'results', 'identifier_closed_loop_batch.csv'));

fprintf('Closed-loop identifier batch complete.\n');
fprintf('Average eta error: %.4f\n', closedLoopResult.averageEtaError);
fprintf('Decision match rate: %.2f%%\n', 100 * closedLoopResult.decisionMatchRate);
fprintf('Controllability classification match rate: %.2f%%\n', 100 * closedLoopResult.controllabilityMatchRate);
end

function tf = is_strictly_conservative(oracleDecision, identifiedDecision)
order = containers.Map( ...
    {'NORMAL', 'RETURN', 'DIVERT', 'STABILIZE', 'EGRESS_PREP', 'UNRECOVERABLE'}, ...
    [1 2 3 4 5 6]);
tf = order(upper(identifiedDecision)) > order(upper(oracleDecision));
end

function tf = is_more_aggressive(modeA, modeB)
order = containers.Map( ...
    {'NORMAL', 'RETURN', 'DIVERT', 'STABILIZE', 'EGRESS_PREP', 'UNRECOVERABLE'}, ...
    [1 2 3 4 5 6]);
tf = order(upper(modeA)) < order(upper(modeB));
end

function tf = is_dangerous_mismatch(oracleDecision, identifiedDecision, confidence)
oracleDecision = upper(oracleDecision);
identifiedDecision = upper(identifiedDecision);
tf = (any(strcmp(oracleDecision, {'UNRECOVERABLE', 'EGRESS_PREP'})) && strcmp(identifiedDecision, 'RETURN')) || ...
    (any(strcmp(oracleDecision, {'DIVERT', 'STABILIZE'})) && strcmp(identifiedDecision, 'RETURN') && confidence > 0.7);
end

function entry = empty_closed_loop_entry()
entry = struct( ...
    'scenarioId', 0, ...
    'scenarioType', '', ...
    'damageCategory', '', ...
    'severity', 0, ...
    'theta_d', zeros(12, 1), ...
    'etaTrue', zeros(1, 4), ...
    'etaHat', zeros(1, 4), ...
    'etaErrorMean', NaN, ...
    'oracleDecision', '', ...
    'identifiedDecision', '', ...
    'decisionMatch', false, ...
    'controllabilityMatch', false, ...
    'trimRiskOracle', '', ...
    'trimRiskIdentified', '', ...
    'trimInfoConsistency', false, ...
    'oracleIsTrimmable', false, ...
    'identifiedIsTrimmable', false, ...
    'identifierConfidence', NaN, ...
    'identifierUncertainty', NaN, ...
    'conservativeDecision', false, ...
    'dangerousMismatch', false, ...
    'conservativeCorrect', false, ...
    'conservativeOvertrigger', false, ...
    'unsafeUndertrigger', false);
end

function tbl = closed_loop_table(summary)
n = numel(summary);
tbl = table( ...
    (1:n).', ...
    string({summary.scenarioType}).', ...
    string({summary.damageCategory}).', ...
    [summary.severity].', ...
    [summary.etaErrorMean].', ...
    string({summary.oracleDecision}).', ...
    string({summary.identifiedDecision}).', ...
    [summary.decisionMatch].', ...
    [summary.controllabilityMatch].', ...
    [summary.trimInfoConsistency].', ...
    [summary.conservativeDecision].', ...
    [summary.conservativeCorrect].', ...
    [summary.conservativeOvertrigger].', ...
    [summary.unsafeUndertrigger].', ...
    [summary.dangerousMismatch].', ...
    [summary.identifierConfidence].', ...
    [summary.identifierUncertainty].', ...
    'VariableNames', {'scenarioId', 'scenarioType', 'damageCategory', 'severity', 'etaErrorMean', ...
    'oracleDecision', 'identifiedDecision', 'decisionMatch', 'controllabilityMatch', ...
    'trimInfoConsistency', 'conservativeDecision', 'conservativeCorrect', ...
    'conservativeOvertrigger', 'unsafeUndertrigger', 'dangerousMismatch', ...
    'identifierConfidence', 'identifierUncertainty'});
end
