function closedLoopSummary = run_identifier_closed_loop_batch()
%RUN_IDENTIFIER_CLOSED_LOOP_BATCH Compare oracle and identified pipelines.

rootDir = fileparts(fileparts(mfilename('fullpath')));
run(fullfile(rootDir, 'scripts', 'init_project.m'));

datasetPath = fullfile(rootDir, 'data', 'identifier_dataset.mat');
if ~isfile(datasetPath)
    generate_identifier_dataset();
end

evalPath = fullfile(rootDir, 'results', 'identifier_eval.mat');
if ~isfile(evalPath)
    evaluate_identifier();
end

D = load(datasetPath, 'identifierDataset');
E = load(evalPath, 'evalEntries');
identifierDataset = D.identifierDataset;
identifierModel = E.evalEntries(1).identifierModel;
identifierConfig = identifierModel.config;

closedLoopSummary = repmat(empty_closed_loop_entry(), numel(identifierDataset.samples), 1);

for i = 1:numel(identifierDataset.samples)
    theta_d = identifierDataset.samples(i).theta_d;
    oracleResult = run_online_assessment_pipeline(theta_d, [], identifierConfig, 'oracle');
    identifiedResult = run_online_assessment_pipeline(theta_d, identifierModel, identifierConfig, 'identified');

    etaTrue = [ ...
        oracleResult.oracle.ctrlMetrics.eta_roll, ...
        oracleResult.oracle.ctrlMetrics.eta_pitch, ...
        oracleResult.oracle.ctrlMetrics.eta_yaw, ...
        oracleResult.oracle.ctrlMetrics.eta_total];
    etaHat = [ ...
        identifiedResult.identified.ctrlMetrics.eta_roll, ...
        identifiedResult.identified.ctrlMetrics.eta_pitch, ...
        identifiedResult.identified.ctrlMetrics.eta_yaw, ...
        identifiedResult.identified.ctrlMetrics.eta_total];

    oracleDecision = oracleResult.oracle.decisionOutput.mode;
    identifiedDecision = identifiedResult.identified.decisionOutput.mode;
    dangerousMismatch = is_dangerous_mismatch(oracleDecision, identifiedDecision, identifiedResult.identified.identifierOutput.confidence);

    closedLoopSummary(i).scenarioId = i;
    closedLoopSummary(i).scenarioType = identifierDataset.samples(i).scenarioInfo.scenarioType;
    closedLoopSummary(i).severity = identifierDataset.samples(i).scenarioInfo.severity;
    closedLoopSummary(i).theta_d = theta_d;
    closedLoopSummary(i).etaTrue = etaTrue;
    closedLoopSummary(i).etaHat = etaHat;
    closedLoopSummary(i).etaErrorMean = mean(abs(etaHat - etaTrue));
    closedLoopSummary(i).oracleDecision = oracleDecision;
    closedLoopSummary(i).identifiedDecision = identifiedDecision;
    closedLoopSummary(i).decisionMatch = identifiedResult.decisionMatch;
    closedLoopSummary(i).controllabilityMatch = identifiedResult.controllabilityMatch;
    closedLoopSummary(i).trimRiskOracle = oracleResult.oracle.trimInfo.trimRiskLevel;
    closedLoopSummary(i).trimRiskIdentified = identifiedResult.identified.trimInfo.trimRiskLevel;
    closedLoopSummary(i).trimInfoConsistency = identifiedResult.trimMatch;
    closedLoopSummary(i).oracleIsTrimmable = oracleResult.oracle.trimInfo.is_trimmable;
    closedLoopSummary(i).identifiedIsTrimmable = identifiedResult.identified.trimInfo.is_trimmable;
    closedLoopSummary(i).identifierConfidence = identifiedResult.identified.identifierOutput.confidence;
    closedLoopSummary(i).identifierUncertainty = identifiedResult.identified.identifierOutput.uncertaintyScore;
    closedLoopSummary(i).conservativeDecision = is_conservative(oracleDecision, identifiedDecision);
    closedLoopSummary(i).dangerousMismatch = dangerousMismatch;
end

summaryTable = closed_loop_table(closedLoopSummary);
save(fullfile(rootDir, 'results', 'identifier_closed_loop_batch.mat'), 'closedLoopSummary', 'summaryTable');
save(fullfile(rootDir, 'results', 'identified_vs_oracle_summary.mat'), 'closedLoopSummary', 'summaryTable');
writetable(summaryTable, fullfile(rootDir, 'results', 'identifier_closed_loop_batch.csv'));

fprintf('Closed-loop identifier batch complete.\n');
fprintf('Average eta error: %.4f\n', mean([closedLoopSummary.etaErrorMean]));
fprintf('Decision match rate: %.2f%%\n', 100 * mean([closedLoopSummary.decisionMatch]));
fprintf('Controllability classification match rate: %.2f%%\n', 100 * mean([closedLoopSummary.controllabilityMatch]));
end

function tf = is_conservative(oracleDecision, identifiedDecision)
order = containers.Map( ...
    {'NORMAL', 'RETURN', 'DIVERT', 'STABILIZE', 'EGRESS_PREP', 'UNRECOVERABLE'}, ...
    [1 2 3 4 5 6]);
tf = order(upper(identifiedDecision)) >= order(upper(oracleDecision));
end

function tf = is_dangerous_mismatch(oracleDecision, identifiedDecision, confidence)
oracleDecision = upper(oracleDecision);
identifiedDecision = upper(identifiedDecision);
tf = (any(strcmp(oracleDecision, {'UNRECOVERABLE', 'EGRESS_PREP'})) && strcmp(identifiedDecision, 'RETURN')) || ...
    (any(strcmp(oracleDecision, {'DIVERT', 'STABILIZE'})) && strcmp(identifiedDecision, 'RETURN') && confidence > 0.7);
end

function entry = empty_closed_loop_entry()
entry = struct( ...
    'scenarioId', 0, ...
    'scenarioType', '', ...
    'severity', 0, ...
    'theta_d', zeros(12, 1), ...
    'etaTrue', zeros(1, 4), ...
    'etaHat', zeros(1, 4), ...
    'etaErrorMean', NaN, ...
    'oracleDecision', '', ...
    'identifiedDecision', '', ...
    'decisionMatch', false, ...
    'controllabilityMatch', false, ...
    'trimRiskOracle', '', ...
    'trimRiskIdentified', '', ...
    'trimInfoConsistency', false, ...
    'oracleIsTrimmable', false, ...
    'identifiedIsTrimmable', false, ...
    'identifierConfidence', NaN, ...
    'identifierUncertainty', NaN, ...
    'conservativeDecision', false, ...
    'dangerousMismatch', false);
end

function tbl = closed_loop_table(summary)
n = numel(summary);
tbl = table( ...
    (1:n).', ...
    string({summary.scenarioType}).', ...
    [summary.severity].', ...
    [summary.etaErrorMean].', ...
    string({summary.oracleDecision}).', ...
    string({summary.identifiedDecision}).', ...
    [summary.decisionMatch].', ...
    [summary.controllabilityMatch].', ...
    [summary.trimInfoConsistency].', ...
    [summary.conservativeDecision].', ...
    [summary.dangerousMismatch].', ...
    [summary.identifierConfidence].', ...
    [summary.identifierUncertainty].', ...
    'VariableNames', {'scenarioId', 'scenarioType', 'severity', 'etaErrorMean', ...
    'oracleDecision', 'identifiedDecision', 'decisionMatch', 'controllabilityMatch', ...
    'trimInfoConsistency', 'conservativeDecision', 'dangerousMismatch', ...
    'identifierConfidence', 'identifierUncertainty'});
end
